language: node_js
node_js: stable
os: linux
dist: bionic
install:
- npm install
script:
- npm run test
after_script: echo 'Script is run'
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: UgmvMFESTSljChdM2rbABuXo5/cRb9r1spTJWcgAeT8M/83lgg98pfaFCS7ShyIHtgiLBSBjhx6vV5oUXXY+tYA4MCnk34lTNyqra2ELSeqGqiM705d5cvCGKvbLDv9J8mz9w9iCC5orrMKBOMjgXERilclAWSl51g6QG7uVGUXMKYiL6VB5AqOMCpVVnmWv1Ud5y4y5QeS099/FCRpsJ/pw2cyGyRWCBayBCwR3Z7E76HFjWTFLj+ZahLxhItcTF5BCKc3Z20Yl3Ez4C9oH8tKavmZu7YkDQQoPwpz48QFo2A44AAxbd0mQtcFd2PspjJvCKmii7DfkuQXjO9YxpiCjzAiv/KsZnMoo0A+QEk3eJlQbkoIpczOAxKeG7DLDkQF+WgaM0dVcOHCK+7KKg2ALGai/U81xQMRvTQ8P0Qnrvd+bjeouoem7ZOgzwhFey8BzL7S1fMRxxnbLrEX4qPBiAVHvtnKPFBrB0IqY/YoJy/L7/qkWzTRX1KJzbOEvHe+ok94lQFSuhOkdb25OErlH6Y8AKyqubq5NWHavpe6F4geESwOrug9yv2b6E8Ifxga1fdb+Kc3JwAjXFIDQjdXnQdy86s9QIKqr1xnywteqUjgxhKSED1YbI+O944y7i729x6Hn8CmeNEIIcFU6ZmRao+4NCPOFyhDmZ0AdYb0=
  app: secondcourse-project
  strategy: git
  on:
    branch: master
after_success: echo 'Build succeed'
