language: node_js
node_js: stable
os: linux
dist: bionic
install:
- npm install
script:
- npm run test
after_script: echo 'Script is run'
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: jA4eCDLjpWy5gPLw8LQZZl9LzlkoNVQM+x6L4YN2ElDfGNtpzKpTMil8EdgyU63PRaMjJn3pzRxDK+HEnC02X4Lv4n6rFQ7bu5joIuBbC6dVbVP7y5aV5UcQri5ahEGxi41CQZnS5vYCkzD/Id4PrDggnMRtIHxNX0wZNrGgAAUUOtEnzEzJ05p5L+ePvmDw8m0KQrRbhFI48rorfVsFbMbhjUmXdPp4nIpdyIjGlNP4AzzT/6BfVMLlYy2vmozIBcCIqAJKxWc1dCIQDybKEOjHZlwEJXB37sR4yXWcgLg0DW46Qxsx7Sg4MLXavbY7L1f+IRtnWNzCooZ+jSCGNe2KOe7YdUFMhhpQGm7i/bPOhJClXd+ntlAcSF6FJiEz7Wf51s+URsabZl6Vvj5Qj1XGmrR7AOB33VkEp5kjTiMyuWZHSNjT0U+u1xeONTDnsuxia4+Ble1qaIxPTiDTd9rZU91zm1xF9vhp7QWffJepHpodv+JiAWaI9sClv255V9SoWOHukXEpjsFQUL47PR9uaW0RqgQtYSqN1Fg43SNwm1On4xDe16JRyFFEjz6G5/906l0QFZJSJ7ENiLoefk7pUGG0GjcaYUFT2d/5cBENsDFz5F0EkSUzrFc8sxWdzWieZX2WT7lj7BGEFJbNFYuYjhXVHZ3rlrKD3apKg+o=
  app: damp-fortress-18039
  on:
    branch: master
after_success: echo 'Build succeed'
