language: node_js
node_js: stable
os: linux
dist: bionic
install:
- npm install
script:
- npm run test
after_script: echo 'Script is run'
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: sSy1F1HHi+YrXjRPYPq1nbsxeTxMwa5vCCj6QNZJNMaHfqnEUqiSiaBMr8AGJ1koLiY5/x/MtEwUYrbG4oQcAhqUPYDoMm2S+KBuFrs+th8rWSK/7KiIrUGgP9p9XfqtGzWKL70Odor7NeVS8xvx+kP6y3lv+bI/BUfwmCCuhdSrQXgQTLC2/3zsS7apHnBxgRxic9HbfSa98IeB+ge9YPYHnh2WNXVbmBqvYxOMRLvt5lQfiij13c90aTQPF4G57cC0oxKlrRyfXUc3Di/6PtbrP9fC9j38o3FE/VoyFshQ/KXBr+HBRW7CfsnFM31V01YSr1JyvdPIWFYuluIM5XPbcSlTxOWGRS+QHnLWHRSO6Q819DXodlUv+4lL5lYOR1alIYgRCJiQeD/Ijt92ekQ7S1jTN8RTF03TpOciTUFeogJXmEz4Ya2vXJWDol1pkOxkggSacGvB/irf7pSJXcceW4L7abUGNuOZmkEkxJWCysp34CDuWm/WziFXG0UeMuvjg/xWzFRLAfWiAxy/b4SxpZEt7xKH/bOmSM2ef+m2lNYhWb/S58OKlpSOszxlGGocrejiV1xIGu4LodtWDntKjZL5xI3cZIQf7ZfXTMI12GJpW3InzihY20QceLs1MpxRiZsjz3SzKM5Vla1D5JE5/QE4N+GWDhrFKjJkmH8=
  app: damp-fortress-18039
  on:
    branch: master
after_success: echo 'Build succeed'
