language: node_js
node_js: stable
os: linux
dist: bionic
install:
- npm install
script:
- npm run test
after_script: echo 'Script is run'
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: mJDLuuHSHGVHxXTm+d7x2CCzssAn0mlHIe78EIas3LXfpybYPC/dwZIvW5sc56lTt9V855TcWoPDqBuMB4lG6Rwmc4luFEbMhxtQvyC2wdy4brRqkkaCcIaqTuA9bFLhnnbtfqo5ImE7CgIZlCqkPM3jnjosUwf+NqCwryuFrl8wuR2ybBVIEU6bIOT55O1cJp/wnRI9asMeM+BZKc9Pt1JlBE4WNMA6FYtLFPNSas0v/lhbOBZmw+4r0glLUc2iZYry4i+mORaPgCATvxqq2NE9CSzcICq/glDCZmuLY4UVADIwBbEQ0z13XQtL9b9CYHGcJQoH0YZDrVFIuThSdPCDxh53oq2xALV/q5WC6gqCKDl+KYKVdYW+J13VLoVHGTQxMTwcKzIpxIARbNiQgLzwlcx1qMVxPsy9OK87nNoPxuiMypJqzWU59Qgm8yd+odA0+un2ZBVGgwpgXt7iTL4j8BJcerLZSFl9fstrPQsvQa8Yn395ZWPksKCQ6pPfg7B+EbRXk70YCEL1OeR1SqgJoVPA94NplW1WMyifEnmMMeZkZVKs9NXtllxsk8LpGzBKL007Gb8L66Ktod0Vt2PEnbT5G5O18t3jBip/LvlYhubkKkEMgan4VonvbGK4Mx8sSDhZ7qCtGfXiPpPnITkh1yKf6xFWzLMBXFlzsMM=
  app: damp-fortress-18039
  on:
    branch: master
after_success: echo 'Build succeed'
