language: node_js
node_js: "stable"
dist: bionic

install:
  - npm install
script:
  - sudo npm start
after_script: "echo 'Scrip is run'"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Z1oQ0rpqJ5IZjOTccytOPSTPD3HPvFGauyeAQ8gHQqy1gLepG3mulmcaLS+gKhjS9oGDKXHIoTNEj52/uPwIXEYA1af9vcDInyz5JA0hzeSyA1ZsI/ZgHTrMbnEyWN3FrC5rXQsmNGVm754YMmqvWSsGJgvCrzhv1UUqwoUmTINOlKJL+0Pw8+RIY7D9VZT2QEaYqNWNcKDfonJt1ar2qx9xve0gQnwsa2/ned0DXxID2hO7CzP0UQLYWlmP0P4lAeDiAsgOZQw8AJJur6wZhYIS2S9bPtWWP2ru3mysCTjpsoCyQJCXKGc93q/1ugIOxFdGO0ZBuNuG4S8TTMSLTzxOR8/tF0CJP+bXuQ29A/whOnASjM6xpF1jRA6AIW9CpQQJYUMt4Im67uYPoreGJAWTIPPkRD33SOiyXPxrdxTUxJ3HDshLnHKUWD0PFScqae0NDAS1ERtP/EKq2pjeadeysB8mIlKOIkVQ/Wz6q9NyCcC1G2PUKFRr6fQCwM0MYOWsK2s7WFXuMXSWqz1Mn+Edf2cm8F4isI0ePbihT+4Ffh+sBpsrZxAbpd7TPWNPWIfIVXI7v6ZjbTw2bW8NUFEWhFtWggnILPJfJP24GlWabt6R6MACpkzriukBtvNykmQX3thSyQNMLjm1SPKlSvPiPFXFU5vd8gimB3P72rI=
  app: secondcourse-project
  strategy: git
  on:
    branch: release
after_success: echo 'Build succeed'
