language: node_js
node_js: stable
os: linux
dist: bionic
install:
- npm install
script:
- test-cov
after_script: echo test succed
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: BMcvo4+qAKZupNJGsddzBb9lwNTIEjTag1NELnN8SYiFLfBEGcplyiUDcWh3jmxzVwUIuWZaRnHhUx6eTRGUQnLZF2eHicvCzaeicc6aF+Fn4Ceb+Ia0SkEpOfSZx81X+ta7QRBrKwRjs7PA2RkIUFSJYfUAN4LhQdsxfoPTv5BN7kFQeQXfDn9un5dJOBnxbU/wSt8kOp9qgROaKTP5+uhtwPURQjbo2EDNVZKdQn9mquIRVMYAOfuEPP6zP3+VgzfVHfjeUb/S6YKBSYGTqS4SIf6T5cMbVddge3gsQHJvOQZQc/twuesLogyGgCzkzZpynWuGjtk6FdpGNRdu3kW+1wZepibtC6J2hwE3BJi77RB7elpDAa81RT+HVMfvyCUT5hZlm636r+IsCb2W+FyLpMFL52lhbPjq07vTk1IUycRmw421vrH5Ze6sxt/0cLNDhu3WcwF0qH+ZqyQVNrKOVss//IPSJkJFNXeGmaHLfT7+a56ckz6/DHP+wk/rwfGwJ4/fDRMG9RUfNwccEg11+7rjMW6OAud20UsL2M0FDT0AH4WM5aIHf1nZ2NULE9VadIryAkZJ/ZUmB3lWGUF/nTanKvbrWCuzThaSBnNqJqbCRwbwFzsynjvoj+OVBc1eqQ1BcSivwn0lbTuaPknhMLtwFrq8fq74eBpRR1Q=
  app: secondcourse-project
  strategy: git
  on:
    branch: release
after_success: echo "done"
